### ISSUE TITLE
openRL   **typed_msgSend(cls, _cmd, app, url, options);**     crash

### ISSUE THREAD

**Issue by Winter-Yang** [mdsb100/YTXModule#2]
- (BOOL)ytxmodule_application:(UIApplication _)app openURL:(NSURL *)url options:(NSDictionary<NSString_, id> _)options NS_AVAILABLE_IOS(9_0); // no equiv. notification. return NO if the application can't open for some reaso
  {
  BOOL result = YES;
  SEL ytx_selector = NSSelectorFromString([NSString stringWithFormat:@"ytxmodule_%@", NSStringFromSelector(_cmd)]);
  SELECTOR_IS_EQUAL(ytx_selector, _cmd)
  if (imp1 != imp2) {
      result = ((BOOL (_)(id, SEL, id, id, id))(void _)objc_msgSend)(self, ytx_selector, app, url, options);
  }
  id (_typed_msgSend)(id, SEL, id, id, id) = (void *)objc_msgSend;
  for (Class cls in YTXModuleClasses) {
      if ([cls respondsToSelector:_cmd]) {
         ##  typed_msgSend(cls, _cmd, app, url, options);   crash
      }
  }
  
  for (id obj in YTXModuleObjects) {
      if ([obj respondsToSelector:_cmd]) {
          typed_msgSend(obj, _cmd, app, url, options);
      }
  }
  return result;
  }

YTXTestModule.m
use:
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options{
  NSLog(@"----------------------");
  return YES;

}

**Comment by mdsb100** [comment]
Fix. 710d78d3b967647dd685fec034e5ac49e00d2602
